apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  containers:
    - name: writer-container
      image: writer-image
      volumeMounts:
        - mountPath: /shared
          name: shared-volume
    - name: reader-container
      image: reader-image
      volumeMounts:
        - mountPath: /shared
          name: shared-volume

