apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: container-name
    image: image-name
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "200m"
        memory: "400Mi"

